/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.configurarpartida.vista;

import itson.configurarpartida.controlador.ControladorConfigurarPartida;
import itson.rummypresentacion.utils.EstiloSliderRummy;
import itson.rummypresentacion.utils.TipoVista;
import java.awt.Color;
import java.awt.Font;
import java.util.Hashtable;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import itson.configurarpartida.modelo.IModeloConfiguracion;
import itson.configurarpartida.modelo.IObserverConfiguracion;

/**
 *
 * @author Dana Chavez
 */
public class UI_ConfigurarPartida extends javax.swing.JFrame implements IObserverConfiguracion {

    private ControladorConfigurarPartida controlador;
    private String ultimoMensajeError = null;
    private boolean navegando = false;

    private final Font FUENTE_NUMEROS = new Font("Segoe UI", Font.BOLD, 36);
    private final Color COLOR_NUMEROS = new Color(255, 221, 154);

    /**
     * Creates new form ConfigurarPartida
     */
    public UI_ConfigurarPartida(ControladorConfigurarPartida controlador) {
        this.controlador = controlador;
        initComponents();
        personalizarSliders();
        setLocationRelativeTo(null);
    }

    /**
     * Configura manualmente los sliders generados por NetBeans para que se vean
     * bonitos.
     */
    private void personalizarSliders() {
        configurarEstiloSlider(jSliderRangoFichas, 10, 13, 12);

        configurarEstiloSlider(jSliderComodines, 2, 8, 3);
    }

    private void configurarEstiloSlider(javax.swing.JSlider slider, int min, int max, int valInicial) {
        slider.setMinimum(min);
        slider.setMaximum(max);
        slider.setValue(valInicial);

        slider.setUI(new EstiloSliderRummy(slider));

        slider.setOpaque(false);
        slider.setMajorTickSpacing(1);
        slider.setPaintTicks(false);
        slider.setPaintLabels(true);
        slider.setSnapToTicks(true);

        Hashtable<Integer, JLabel> labels = new Hashtable<>();
        for (int i = min; i <= max; i++) {
            JLabel lbl = new JLabel(String.valueOf(i));
            lbl.setFont(FUENTE_NUMEROS);
            lbl.setForeground(COLOR_NUMEROS);
            labels.put(i, lbl);
        }
        slider.setLabelTable(labels);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderComodines = new javax.swing.JSlider();
        jSliderRangoFichas = new javax.swing.JSlider();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 743));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSliderComodines, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 630, -1));
        getContentPane().add(jSliderRangoFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 630, -1));

        jButtonSiguiente.setBackground(new java.awt.Color(194, 218, 233));
        jButtonSiguiente.setForeground(new java.awt.Color(74, 68, 89));
        jButtonSiguiente.setText("SIGUIENTE");
        jButtonSiguiente.setActionCommand("jButtonSiguiente");
        jButtonSiguiente.setBorder(null);
        jButtonSiguiente.setBorderPainted(false);
        jButtonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSiguiente.setMaximumSize(new java.awt.Dimension(242, 55));
        jButtonSiguiente.setMinimumSize(new java.awt.Dimension(242, 55));
        jButtonSiguiente.setPreferredSize(new java.awt.Dimension(242, 55));
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, -1, -1));

        jButtonRegresar.setBackground(new java.awt.Color(194, 218, 233));
        jButtonRegresar.setForeground(new java.awt.Color(74, 68, 89));
        jButtonRegresar.setText("REGRESAR");
        jButtonRegresar.setBorder(null);
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.setMaximumSize(new java.awt.Dimension(242, 55));
        jButtonRegresar.setMinimumSize(new java.awt.Dimension(242, 55));
        jButtonRegresar.setPreferredSize(new java.awt.Dimension(242, 55));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurarPartida.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if (controlador != null) {
            Integer fichas = Integer.valueOf(jSliderRangoFichas.getValue());
            Integer comodines = Integer.valueOf(jSliderComodines.getValue());

            controlador.confirmarConfiguracion(fichas, comodines);
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        if (controlador != null) {
            controlador.volverAlMenu();
        }
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    @Override
    public void update(IModeloConfiguracion modelo) {
        SwingUtilities.invokeLater(() -> {
            if (navegando) {
                return;
            }

            if (modelo.getVistaActual() == TipoVista.CONFIGURAR_PARTIDA) {
                this.setVisible(true);
            } else {
                this.setVisible(false);
            }

            if (modelo.isConfiguracionExitosa()) {
                navegando = true; 

                this.setVisible(false);
                this.dispose();

                controlador.navegarAlJuego();
                return;
            }

            String mensajeError = modelo.getMensajeError();
            if (mensajeError != null
                    && !mensajeError.isBlank()
                    && !mensajeError.equals(ultimoMensajeError)) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        mensajeError,
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );

                ultimoMensajeError = mensajeError;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JSlider jSliderComodines;
    private javax.swing.JSlider jSliderRangoFichas;
    // End of variables declaration//GEN-END:variables
}
