/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.configurarpartida.vista;

import itson.configurarpartida.controlador.ControladorConfigurarPartida;
import itson.rummypresentacion.utils.TipoVista;
import javax.swing.SwingUtilities;
import itson.configurarpartida.modelo.IModeloConfiguracion;
import itson.configurarpartida.modelo.IObserverConfiguracion;

/**
 *
 * @author Dana Chavez
 */
public class UI_MenuRummy extends javax.swing.JFrame implements IObserverConfiguracion {

    private ControladorConfigurarPartida controlador;

    /**
     * Creates new form MenuRummy
     */
    public UI_MenuRummy(ControladorConfigurarPartida controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrearPartida = new javax.swing.JButton();
        jButtonUnirsePartida = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 743));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCrearPartida.setBackground(new java.awt.Color(248, 222, 222));
        jButtonCrearPartida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonCrearPartida.setForeground(new java.awt.Color(74, 68, 89));
        jButtonCrearPartida.setText("CREAR PARTIDA");
        jButtonCrearPartida.setBorder(null);
        jButtonCrearPartida.setBorderPainted(false);
        jButtonCrearPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearPartida.setMaximumSize(new java.awt.Dimension(340, 27));
        jButtonCrearPartida.setPreferredSize(new java.awt.Dimension(340, 61));
        jButtonCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        jButtonUnirsePartida.setBackground(new java.awt.Color(248, 222, 222));
        jButtonUnirsePartida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonUnirsePartida.setForeground(new java.awt.Color(74, 68, 89));
        jButtonUnirsePartida.setText("UNIRSE A PARTIDA");
        jButtonUnirsePartida.setBorder(null);
        jButtonUnirsePartida.setBorderPainted(false);
        jButtonUnirsePartida.setPreferredSize(new java.awt.Dimension(340, 61));
        jButtonUnirsePartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnirsePartidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUnirsePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuRummy.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPartidaActionPerformed
        if (controlador != null) {
            controlador.irAConfigurarPartida();
        }
    }//GEN-LAST:event_jButtonCrearPartidaActionPerformed

    private void jButtonUnirsePartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnirsePartidaActionPerformed
        if (controlador != null) {
            controlador.unirseAPartida();
        }
    }//GEN-LAST:event_jButtonUnirsePartidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearPartida;
    private javax.swing.JButton jButtonUnirsePartida;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(IModeloConfiguracion modelo) {
        SwingUtilities.invokeLater(() -> {
            if (modelo.getVistaActual() == TipoVista.MENU_PRINCIPAL) {
                this.setVisible(true);
            } else {
                this.setVisible(false);
            }
        });
    }
}
