/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.solicitarinicio.vista;

import itson.rummydtos.JugadorDTO;
import itson.rummypresentacion.utils.TipoVista;
import itson.solicitarinicio.controlador.ControladorSalaEspera;
import itson.solicitarinicio.modelo.IModeloSalaEspera;
import itson.solicitarinicio.modelo.IObserverSalaEspera;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Dana Chavez
 */
public class UI_SalaEspera extends javax.swing.JFrame implements IObserverSalaEspera {

    private ControladorSalaEspera controlador;
    private JPanel[] panelesOponentes;

    public UI_SalaEspera(ControladorSalaEspera controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);

        panelesOponentes = new JPanel[]{jPanelOponente1, jPanelOponente2, jPanelOponente3};

        prepararPanel(jPanelJugadorLocal);
        for (JPanel p : panelesOponentes) {
            prepararPanel(p);
        }

        jButtonComenzar.addActionListener(e -> controlador.clickComenzarPartida());
    }

    private void prepararPanel(JPanel panel) {
        panel.setOpaque(false);
        panel.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOponente3 = new javax.swing.JPanel();
        jPanelOponente2 = new javax.swing.JPanel();
        jPanelOponente1 = new javax.swing.JPanel();
        jPanelJugadorLocal = new javax.swing.JPanel();
        jButtonComenzar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 743));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelOponente3Layout = new javax.swing.GroupLayout(jPanelOponente3);
        jPanelOponente3.setLayout(jPanelOponente3Layout);
        jPanelOponente3Layout.setHorizontalGroup(
            jPanelOponente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanelOponente3Layout.setVerticalGroup(
            jPanelOponente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelOponente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 230, 110));

        javax.swing.GroupLayout jPanelOponente2Layout = new javax.swing.GroupLayout(jPanelOponente2);
        jPanelOponente2.setLayout(jPanelOponente2Layout);
        jPanelOponente2Layout.setHorizontalGroup(
            jPanelOponente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanelOponente2Layout.setVerticalGroup(
            jPanelOponente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelOponente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 230, 110));

        javax.swing.GroupLayout jPanelOponente1Layout = new javax.swing.GroupLayout(jPanelOponente1);
        jPanelOponente1.setLayout(jPanelOponente1Layout);
        jPanelOponente1Layout.setHorizontalGroup(
            jPanelOponente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanelOponente1Layout.setVerticalGroup(
            jPanelOponente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelOponente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 230, 110));

        javax.swing.GroupLayout jPanelJugadorLocalLayout = new javax.swing.GroupLayout(jPanelJugadorLocal);
        jPanelJugadorLocal.setLayout(jPanelJugadorLocalLayout);
        jPanelJugadorLocalLayout.setHorizontalGroup(
            jPanelJugadorLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanelJugadorLocalLayout.setVerticalGroup(
            jPanelJugadorLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelJugadorLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 240, 110));

        jButtonComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boton_comenzar.png"))); // NOI18N
        jButtonComenzar.setBorder(null);
        jButtonComenzar.setContentAreaFilled(false);
        jButtonComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 400, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_sala.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComenzar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanelJugadorLocal;
    private javax.swing.JPanel jPanelOponente1;
    private javax.swing.JPanel jPanelOponente2;
    private javax.swing.JPanel jPanelOponente3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(IModeloSalaEspera modelo) {
        System.out.println("[UI_SalaEspera] Recibida actualización de modelo.");

        SwingUtilities.invokeLater(() -> {

            if (modelo.getVistaActual() != TipoVista.SALA_ESPERA) {
                this.setVisible(false);
                return;
            } else {
                this.setVisible(true);
            }

            limpiarPaneles();

            List<JugadorDTO> jugadores = modelo.getJugadoresEnSala();
            String miId = modelo.getMiId();

            int oponenteIndex = 0;

            for (JugadorDTO j : jugadores) {
                PanelJugadorSala panelVisual = new PanelJugadorSala(j);

                if (j.getId().equals(miId)) {
                    jPanelJugadorLocal.add(panelVisual, BorderLayout.CENTER);
                } else {
                    if (oponenteIndex < panelesOponentes.length) {
                        panelesOponentes[oponenteIndex].add(panelVisual, BorderLayout.CENTER);
                        oponenteIndex++;
                    }
                }
            }

            boolean puedeIniciar = jugadores.size() >= 2;
            jButtonComenzar.setEnabled(puedeIniciar);

            if (puedeIniciar) {
                jButtonComenzar.setText("COMENZAR PARTIDA");
            } else {
                jButtonComenzar.setText("Esperando jugadores...");
            }

            this.revalidate();
            this.repaint();
        });
    }

    private void limpiarPaneles() {
        jPanelJugadorLocal.removeAll();
        for (JPanel p : panelesOponentes) {
            p.removeAll();
        }
    }
}
